# Generated by nvc 1.8-devel

all: /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST.elab /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST.elab /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES-body /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.TESTUTIL /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.TESTUTIL-body

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/_WORK.KECCAK_RHO_TEST.final.so /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST.elab: /usr/local/lib/nvc/std/STD.STANDARD /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO
	nvc -e keccak_rho_test

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/_WORK.KECCAK_THETA_TEST.final.so /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST.elab: /usr/local/lib/nvc/std/STD.STANDARD /usr/local/lib/nvc/ieee/IEEE.STD_LOGIC_1164 /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA
	nvc -e keccak_theta_test

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO: src/keccak_rho.vhdl /usr/local/lib/nvc/std/STD.STANDARD /usr/local/lib/nvc/ieee/IEEE.STD_LOGIC_1164 /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES
	nvc -a src/keccak_rho.vhdl

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA: src/keccak_theta.vhdl /usr/local/lib/nvc/std/STD.STANDARD /usr/local/lib/nvc/ieee/IEEE.STD_LOGIC_1164 /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES
	nvc -a src/keccak_theta.vhdl

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES-body /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES: src/keccak_types.vhdl /usr/local/lib/nvc/std/STD.STANDARD /usr/local/lib/nvc/ieee/IEEE.STD_LOGIC_1164
	nvc -a src/keccak_types.vhdl

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_RHO_TEST: test/keccak_rho_test.vhdl /usr/local/lib/nvc/std/STD.TEXTIO /usr/local/lib/nvc/std/STD.STANDARD /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.TESTUTIL /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES
	nvc -a test/keccak_rho_test.vhdl

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST-ARCH /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_THETA_TEST: test/keccak_theta_test.vhdl /usr/local/lib/nvc/std/STD.TEXTIO /usr/local/lib/nvc/std/STD.STANDARD /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.TESTUTIL /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES
	nvc -a test/keccak_theta_test.vhdl

/mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.TESTUTIL-body /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.TESTUTIL: test/testutil.vhdl /usr/local/lib/nvc/std/STD.TEXTIO /usr/local/lib/nvc/std/STD.STANDARD /usr/local/lib/nvc/ieee/IEEE.STD_LOGIC_TEXTIO /usr/local/lib/nvc/ieee/IEEE.STD_LOGIC_1164 /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work/WORK.KECCAK_TYPES
	nvc -a test/testutil.vhdl

clean:
	rm -r /mnt/d/Users/Niklas/Documents/Studium/Abschlussarbeit/keccak/sha3-vhdl/work

run: all
	nvc -r keccak_rho_test

wave: all
	nvc -r -w keccak_rho_test

.PHONY: all run wave clean

-include local.mk
